### ISSUE TITLE
Text and Tables do not follow the right margin requirements for the page

### ISSUE THREAD

**Issue by WSU-Car** [WSULib/wsu-dt-latex#2]
Hello,

Thanks for creating the template.
I am not sure if this template is still being updated. However, I wanted to reach out and see if there is a possibility to update the template to fix the right margin issues. It appears that the text runs out of the page (on the right side).

Thanks,
Prabhjot

**Comment by helloitsclayton** [comment]
Hi Prabhjot,

Mostly I only look at the template when contacted by grad students, so I haven't been actively maintaining it. I'll see if I can solve this issue. I'm going to compare the code in this template with the thesis created by another student a few years ago: https://github.com/aarontwillcock/wsu-ms-cs-tufc

Feel free to do the same, and let me know if you figure it out before I do.

Best,
Clayton

**Comment by WSU-Car** [comment]
Thanks for the quick response. I will do the compare on my end too and let you know if I find anything. Thanks again. This is very helpful.

**Comment by helloitsclayton** [comment]
After having poked around in the code  it looks like the overflow only occurs in a few specific cases, one of which being tables. The other apparent case in the template as it exists (the listing of degrees in the abstract section) is also a table. I think that chapter/section/etc. titles will also exhibit this behavior.
There doesn't seem to be a good fix, and the issue with tables is a longstanding one in LaTeX. I noticed some other little things I wanted to fix, so I'll probably update the template so the cell contents aren't very large URLs that LaTeX won't want to add line breaks to.

**Comment by helloitsclayton** [comment]
I've updated to compensate for this issue, as well as fixing another issue I found with internal linking. Marking as resolved.

**Comment by WSU-Car** [comment]
Thanks a lot! This template will make writing a Thesis so much better. I really appreciate the work that went into creating this template.
